services:
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - redis
      - grobid

  redis:
    image: redis:alpine

  grobid:
    image: grobid/grobid:0.9.0-crf
    ports:
      - "8070:8070"